/*Changer le statut d'une commande (commande, statut)*/

CREATE OR REPLACE PROCEDURE changerLeStatutDuneCommande(p_idcommande IN COMMANDE.ID%TYPE )
IS
	v_idStatutCommande number;	
BEGIN
	SELECT REFSTATUTCOMMANDE INTO v_idStatutCommande
	FROM COMMANDE_STATUTCOMMANDE
	WHERE REFCOMMANDE = p_idcommande;
	

	IF REFSTATUTCOMMANDE = 1 THEN
	
		UPDATE COMMANDE_STATUTCOMMANDE
		SET REFSTATUTCOMMANDE = REFSTATUTCOMMANDE + 1
		WHERE REFCOMMANDE = p_idcommande;
		
		
	ELSE IF REFSTATUTCOMMANDE = 2 THEN
	
		UPDATE COMMANDE_STATUTCOMMANDE
		SET REFSTATUTCOMMANDE = REFSTATUTCOMMANDE + 1
		WHERE REFCOMMANDE = p_idcommande;
		
	ELSE 
		UPDATE COMMANDE_STATUTCOMMANDE
		SET REFSTATUTCOMMANDE = REFSTATUTCOMMANDE + 1
		WHERE REFCOMMANDE = p_idcommande;
	
	END IF;
	

END changerLeStatutDuneCommande;